apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-sap-sample
  labels:
    app: node-sap-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-sap-sample
  template:
    metadata:
      labels:
        app: node-sap-sample
    spec:
      containers:
      - name: node-sap-sample
        image: leux1/node-sap-sample
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 3001
        env:
          - name: HOST
            valueFrom: 
              configMapKeyRef:
                name: node-sap-sample
                key: host
          - name: PORT
            valueFrom: 
              configMapKeyRef:
                name: node-sap-sample
                key: port
---

apiVersion: v1
kind: Service
metadata:
  name: node-sap-sample
  labels: 
    app: node-sap-sample
spec:
  selector:
    app: node-sap-sample
  ports:
  - name: http
    port: 3001
    targetPort: 3001

        
